<?php

namespace LaunchDarkly\HashValueExposer\Tests;

use PHPUnit\Framework\TestCase;
use Eris\Generator;
use Eris\TestTrait;
use LaunchDarkly\HashValueExposer\CalculateHashValue;
use LaunchDarkly\HashValueExposer\MurmurHash3;

/**
 * Property-based tests for CalculateHashValue implementation
 * Feature: hash-value-exposure
 */
class CalculateHashValuePbtTest extends TestCase
{
    use TestTrait;
    
    /**
     * Feature: hash-value-exposure, Property 9: Cross-Platform Bucket Consistency
     * 
     * @test
     */
    public function testProperty9CrossPlatformBucketConsistency(): void
    {
        /**
         * Validates: Requirements 8.2
         * 
         * For any valid input (flag key, context key, salt), when the same inputs 
         * are provided to both Node.js and PHP implementations, both should produce 
         * identical bucket values (within floating-point precision tolerance of 0.000001).
         * 
         * Since we can't directly call Node.js from PHP, we verify against known
         * test vectors that were generated by the Node.js implementation.
         */
        
        // Load test vectors from shared JSON file
        $testVectorsPath = __DIR__ . '/../../../test-vectors.json';
        $this->assertFileExists($testVectorsPath, 'Test vectors file must exist');
        
        $testVectorsJson = file_get_contents($testVectorsPath);
        $testVectors = json_decode($testVectorsJson, true);
        
        $this->assertIsArray($testVectors, 'Test vectors must be valid JSON');
        $this->assertArrayHasKey('bucketValueExamples', $testVectors, 'Test vectors must have bucketValueExamples array');
        
        // Test against all known bucket value examples
        foreach ($testVectors['bucketValueExamples'] as $example) {
            $flagKey = $example['flagKey'];
            $contextKey = $example['contextKey'];
            $salt = $example['salt'];
            $expectedHashValue = $example['expectedHashValue'];
            $expectedBucketValue = $example['expectedBucketValue'];
            
            $result = CalculateHashValue::calculate($flagKey, $contextKey, $salt);
            
            // Verify hash value matches
            $this->assertEquals(
                $expectedHashValue,
                $result['hashValue'],
                sprintf(
                    'Hash value mismatch for "%s". Expected %d, got %d',
                    $example['description'],
                    $expectedHashValue,
                    $result['hashValue']
                )
            );
            
            // Verify bucket value matches (within floating-point precision tolerance)
            $tolerance = 0.000001;
            $this->assertEqualsWithDelta(
                $expectedBucketValue,
                $result['bucketValue'],
                $tolerance,
                sprintf(
                    'Bucket value mismatch for "%s". Expected %f, got %f',
                    $example['description'],
                    $expectedBucketValue,
                    $result['bucketValue']
                )
            );
        }
    }
    
    /**
     * Property test: Bucket value formula correctness
     * 
     * @test
     */
    public function testBucketValueFormulaCorrectness(): void
    {
        /**
         * For any hash value, when computing the bucket value, the result should equal 
         * (abs(hash) % 100000) / 100000.0 where abs() handles negative values correctly.
         */
        $this->forAll(
            Generator\string(),
            Generator\string(),
            Generator\string()
        )->then(function (string $flagKey, string $contextKey, string $salt): void {
            // Skip empty flag keys and context keys as they would be invalid
            if (empty($flagKey) || empty($contextKey)) {
                return;
            }
            
            $result = CalculateHashValue::calculate($flagKey, $contextKey, $salt);
            
            // Manually compute expected bucket value
            $concatenated = "{$flagKey}.{$salt}.{$contextKey}";
            $hash = MurmurHash3::hash($concatenated);
            $expectedBucketValue = (abs($hash) % 100000) / 100000.0;
            
            // Verify bucket value matches formula
            $this->assertEquals($expectedBucketValue, $result['bucketValue']);
        });
    }
    
    /**
     * Property test: Bucket value range invariant
     * 
     * @test
     */
    public function testBucketValueRangeInvariant(): void
    {
        /**
         * For any valid input (flag key, context key, salt), the computed bucket value 
         * should always be in the range [0, 1), meaning greater than or equal to 0 
         * and strictly less than 1.
         */
        $this->forAll(
            Generator\string(),
            Generator\string(),
            Generator\string()
        )->then(function (string $flagKey, string $contextKey, string $salt): void {
            // Skip empty flag keys and context keys as they would be invalid
            if (empty($flagKey) || empty($contextKey)) {
                return;
            }
            
            $result = CalculateHashValue::calculate($flagKey, $contextKey, $salt);
            
            // Verify bucket value is in range [0, 1)
            $this->assertGreaterThanOrEqual(0, $result['bucketValue']);
            $this->assertLessThan(1, $result['bucketValue']);
        });
    }
    
    /**
     * Property test: Bucket value precision
     * 
     * @test
     */
    public function testBucketValuePrecision(): void
    {
        /**
         * For any computed bucket value, the value should be a floating-point number 
         * with at least 5 decimal places of precision (due to division by 100000.0).
         */
        $this->forAll(
            Generator\string(),
            Generator\string(),
            Generator\string()
        )->then(function (string $flagKey, string $contextKey, string $salt): void {
            // Skip empty flag keys and context keys as they would be invalid
            if (empty($flagKey) || empty($contextKey)) {
                return;
            }
            
            $result = CalculateHashValue::calculate($flagKey, $contextKey, $salt);
            
            // Verify bucket value is a float
            $this->assertIsFloat($result['bucketValue']);
            
            // Verify precision by checking that the bucket value can represent
            // values with at least 5 decimal places
            // Since bucket value = (hash % 100000) / 100000.0, it can represent
            // values like 0.00001, 0.00002, etc.
            
            // Convert back to the integer that was divided by 100000
            $scaled = (int)round($result['bucketValue'] * 100000);
            
            // Verify that when we divide back, we get the same value
            // (within floating point precision)
            $reconstructed = $scaled / 100000.0;
            $this->assertEqualsWithDelta($result['bucketValue'], $reconstructed, 1e-10);
            
            // Verify the scaled value is an integer in valid range
            $this->assertGreaterThanOrEqual(0, $scaled);
            $this->assertLessThan(100000, $scaled);
        });
    }
}
