<?php

namespace LaunchDarkly\HashValueExposer\Tests;

use PHPUnit\Framework\TestCase;
use Eris\Generator;
use Eris\TestTrait;
use LaunchDarkly\HashValueExposer\MurmurHash3;

/**
 * Property-based tests for MurmurHash3 implementation
 * Feature: hash-value-exposure
 */
class MurmurHash3PbtTest extends TestCase
{
    use TestTrait;
    
    /**
     * Feature: hash-value-exposure, Property 1: Cross-Platform Hash Consistency
     * 
     * @test
     */
    public function testProperty1CrossPlatformHashConsistency(): void
    {
        /**
         * Validates: Requirements 1.3, 8.1
         * 
         * For any input string, when the same string is hashed using both the Node.js 
         * and PHP implementations with the same seed, both implementations should 
         * produce identical hash values.
         * 
         * Since we can't directly call Node.js from PHP, we verify against known
         * test vectors that were generated by the Node.js implementation.
         */
        
        // Load test vectors from shared JSON file
        $testVectorsPath = __DIR__ . '/../../../test-vectors.json';
        $this->assertFileExists($testVectorsPath, 'Test vectors file must exist');
        
        $testVectorsJson = file_get_contents($testVectorsPath);
        $testVectors = json_decode($testVectorsJson, true);
        
        $this->assertIsArray($testVectors, 'Test vectors must be valid JSON');
        $this->assertArrayHasKey('vectors', $testVectors, 'Test vectors must have vectors array');
        
        // Test against all known vectors
        foreach ($testVectors['vectors'] as $vector) {
            // Skip vectors without expected hash (not yet filled)
            if ($vector['expectedHash'] === null) {
                continue;
            }
            
            $input = $vector['input'];
            $seed = $vector['seed'];
            $expectedHash = $vector['expectedHash'];
            
            $actualHash = MurmurHash3::hash($input, $seed);
            
            $this->assertEquals(
                $expectedHash,
                $actualHash,
                sprintf(
                    'Hash mismatch for input "%s" with seed %d. Expected %d, got %d',
                    $vector['description'],
                    $seed,
                    $expectedHash,
                    $actualHash
                )
            );
        }
    }
    
    /**
     * Property test: Hash output range
     * 
     * @test
     */
    public function testHashOutputRange(): void
    {
        /**
         * For any input string, the MurmurHash3 function should return a value
         * that fits within a signed 32-bit integer range.
         */
        $this->forAll(
            Generator\string(),
            Generator\int()
        )->then(function (string $inputString, int $seed): void {
            $hash = MurmurHash3::hash($inputString, $seed);
            
            // Verify hash is within signed 32-bit integer range
            $MIN_INT32 = -2147483648;
            $MAX_INT32 = 2147483647;
            
            $this->assertGreaterThanOrEqual($MIN_INT32, $hash);
            $this->assertLessThanOrEqual($MAX_INT32, $hash);
            $this->assertIsInt($hash);
        });
    }
    
    /**
     * Property test: Deterministic hashing
     * 
     * @test
     */
    public function testDeterministicHashing(): void
    {
        /**
         * For any input string and seed, hashing the same input multiple times
         * should always produce the same result.
         */
        $this->forAll(
            Generator\string(),
            Generator\int()
        )->then(function (string $inputString, int $seed): void {
            $hash1 = MurmurHash3::hash($inputString, $seed);
            $hash2 = MurmurHash3::hash($inputString, $seed);
            
            $this->assertEquals($hash1, $hash2, 'Hash should be deterministic');
        });
    }
}
